import { SYNTHETIC_READ_MODEL } from "./fixtures.js";

const ROUTES = [["today", "Сегодня"], ["inbox", "Входящие"], ["calendar", "Календарь"], ["plan", "План / граф"], ["tasks", "Задачи"], ["memory", "Память"], ["time", "Время"], ["reviews", "Ревью"], ["decisions", "Решения"], ["health", "Здоровье"], ["sessions", "Сеансы"]];
const READ_ROUTE = { inbox: "inbox", calendar: "calendar", plan: "workgraph", tasks: "tasks", memory: "memory-metadata", time: "time", reviews: "reviews", health: "health" };
const READ_SCHEMA = "command-center-read-model.v1";
const SESSION_SCHEMA = "ui-channel-session.v1";
const COMPOSER_SCHEMA = "composer-admission-result.v1";
const CHAT_RESULT_SCHEMA = "assistant-turn-result.v1";
const MAX_ITEMS = 100;
const MAX_STRING = 256;
const MAX_DEPTH = 8;
const MAX_NODES = 1000;
const MAX_KEYS = 32;
const SENTINEL = /RAW(?:_|\s|-)?PD|QWEN(?:_|\s|-)?(?:OUTPUT|RESULT)|PERSONAL(?:_|\s|-)?DATA|PD(?:_|\s|-)?SENTINEL/i;
const state = { model: null, controller: "degraded_read_only", route: routeFromLocation(), auth: null, synthetic: syntheticMode(), approval: null };
const $ = (id) => document.getElementById(id);
const text = (value, limit = MAX_STRING) => typeof value === "string" ? value.slice(0, limit) : "";

function routeFromLocation() { if (typeof window === "undefined") return "today"; const value = new URLSearchParams(window.location.search).get("route"); return ROUTES.some(([id]) => id === value) ? value : "today"; }
function syntheticMode() { return typeof window !== "undefined" && new URLSearchParams(window.location.search).get("synthetic") === "1"; }
function nonce(prefix) { const random = typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID().replaceAll("-", "") : `${Date.now()}${Math.random()}`; return `${prefix}_${random}`.slice(0, 128); }
function exactKeys(value, allowed) { return value && typeof value === "object" && !Array.isArray(value) && Object.keys(value).every((key) => allowed.includes(key)); }
function withinBounds(value, depth = 0, state = { nodes: 0 }) {
  if (++state.nodes > MAX_NODES || depth > MAX_DEPTH) return false;
  if (value === null || typeof value === "boolean" || typeof value === "number") return true;
  if (typeof value === "string") return value.length <= MAX_STRING;
  if (Array.isArray(value)) return value.length <= MAX_ITEMS && value.every((item) => withinBounds(item, depth + 1, state));
  if (typeof value === "object") { const keys = Object.keys(value); return keys.length <= MAX_KEYS && keys.every((key) => key.length <= MAX_STRING && withinBounds(value[key], depth + 1, state)); }
  return false;
}
function hasSentinel(value) { if (typeof value === "string") return SENTINEL.test(value); if (Array.isArray(value)) return value.some(hasSentinel); if (value && typeof value === "object") return Object.values(value).some(hasSentinel); return false; }
function validAssistantResult(value) { return withinBounds(value) && exactKeys(value, ["schema_version", "chat_id", "thread_id", "turn_id", "state", "answer", "error_code", "started_at", "completed_at"]) && value.schema_version === CHAT_RESULT_SCHEMA && typeof value.chat_id === "string" && ["pending", "running", "completed", "failed", "cancelled"].includes(value.state) && ((value.state === "completed" && typeof value.answer === "string" && value.answer.length > 0 && !value.error_code) || (["pending", "running"].includes(value.state) && !value.answer && !value.error_code) || (["failed", "cancelled"].includes(value.state) && !value.answer && typeof value.error_code === "string")) && !hasSentinel(value); }
function validApprovalRequired(value) { return withinBounds(value) && exactKeys(value, ["schema_version", "error_code", "request_id", "order_digest", "expires_at"]) && value.schema_version === "owner-approval-required.v1" && value.error_code === "OWNER_APPROVAL_REQUIRED" && typeof value.request_id === "string" && /^[0-9a-f]{32}$/.test(value.request_id) && typeof value.order_digest === "string" && /^sha256:[0-9a-f]{64}$/.test(value.order_digest) && iso(value.expires_at) !== "" && Date.parse(value.expires_at) > Date.now() && !hasSentinel(value); }
function serializeChatOrder(chatId, prompt) { return JSON.stringify({ schema_version: "general-chat-order.v1", chat_id: chatId, prompt, workspace_roots: [], classification: "L0", max_output_bytes: 262144, approval_policy: "never", read_only: true, tools_disabled: true, network_mode: "model_only" }); }
function approvalRetryHeaders(requestId) { return { "X-Owner-Approval-Request-ID": requestId }; }
function renderAssistantResult(value) { const output = $("chat-result"); if (!output) return false; output.hidden = false; const valid = validAssistantResult(value); output.className = valid && value.state === "completed" ? "result" : "result error"; output.textContent = valid ? (value.state === "completed" ? `Ответ ChatGPT: ${text(value.answer, 1000)}` : `ChatGPT: ${text(value.error_code, 120)}.`) : "Ответ ChatGPT отклонён: нарушен bounded chat-контракт."; return valid; }
function iso(value) { return typeof value === "string" && !Number.isNaN(Date.parse(value)) ? value : ""; }
function validSession(value) { return withinBounds(value) && exactKeys(value, ["schema_version", "session_id", "channel_id", "token", "client_nonce", "origin", "host", "issued_at", "expires_at", "ephemeral", "persistent"]) && value.schema_version === SESSION_SCHEMA && ["session_id", "channel_id", "token", "client_nonce", "origin", "host"].every((key) => typeof value[key] === "string" && value[key].length > 0 && value[key].length <= MAX_STRING) && iso(value.issued_at) !== "" && iso(value.expires_at) !== "" && value.ephemeral === true && value.persistent === false && !hasSentinel(value); }
function emptyModel(route = state.route) { return { schema_version: READ_SCHEMA, route, generated_at: "", items: [], metrics: {}, health: null, state: "degraded_read_only" }; }
function visibleCard(id, title, detail, status, source, privacy = "SAFE", coverage = "complete", kind = "metadata") { const card = { id: text(id), title: text(title), detail: text(detail), status: text(status), source: text(source), privacy: text(privacy), coverage: text(coverage), kind: text(kind) }; return hasSentinel(card) || !card.id ? null : card; }

function validateRead(route, payload) {
  if (!withinBounds(payload) || !payload || payload.schema_version !== READ_SCHEMA || hasSentinel(payload) || !iso(payload.generated_at)) return null;
  const allowed = { inbox: ["schema_version", "items", "generated_at"], calendar: ["schema_version", "items", "generated_at"], workgraph: ["schema_version", "graph_id", "baseline_version", "nodes", "edges", "generated_at"], tasks: ["schema_version", "items", "generated_at"], time: ["schema_version", "active_task_id", "planned_seconds", "spent_seconds", "generated_at"], reviews: ["schema_version", "items", "generated_at"], "memory-metadata": ["schema_version", "items", "generated_at"], health: ["schema_version", "status", "controller_available", "effects_enabled", "generated_at"] }[route];
  if (!allowed || !exactKeys(payload, allowed)) return null;
  const model = { schema_version: READ_SCHEMA, route, generated_at: payload.generated_at, items: [], metrics: {}, health: null, state: "ready" };
  if (route === "health") { if (typeof payload.status !== "string" || typeof payload.controller_available !== "boolean" || typeof payload.effects_enabled !== "boolean") return null; model.health = { status: text(payload.status), controller_available: payload.controller_available, effects_enabled: payload.effects_enabled }; return hasSentinel(model.health) ? null : model; }
  if (route === "time") { if (!Number.isSafeInteger(payload.planned_seconds) || !Number.isSafeInteger(payload.spent_seconds)) return null; model.metrics = { planned_seconds: payload.planned_seconds, spent_seconds: payload.spent_seconds, active_task_id: text(payload.active_task_id) }; return model; }
  if (route === "workgraph") { if (!Array.isArray(payload.nodes) || !Array.isArray(payload.edges) || payload.nodes.length > MAX_ITEMS || payload.edges.length > MAX_ITEMS) return null; if (payload.nodes.some((node) => !exactKeys(node, ["id", "title", "status", "planned_start", "planned_end"]) || hasSentinel(node) || typeof node.id !== "string" || typeof node.status !== "string")) return null; model.items = payload.nodes.map((node) => visibleCard(node.id, `Work item ${text(node.id, 80)}`, `Статус: ${text(node.status, 80)}`, node.status, "WorkGraph", "SAFE", "complete", "work")).filter(Boolean); return hasSentinel(model) ? null : model; }
  if (!Array.isArray(payload.items) || payload.items.length > MAX_ITEMS) return null;
  if (route === "inbox") { if (payload.items.some((item) => !exactKeys(item, ["id", "summary", "source", "classification", "updated_at"]) || hasSentinel(item) || !iso(item.updated_at))) return null; model.items = payload.items.map((item) => visibleCard(item.id, `Входящее событие ${text(item.id, 80)}`, `Источник: ${text(item.source, 80)}`, "new", item.source, item.classification, "complete", "message")).filter(Boolean); }
  else if (route === "calendar") { if (payload.items.some((item) => !exactKeys(item, ["id", "title", "start", "end", "timezone", "status"]) || hasSentinel(item) || !iso(item.start) || !iso(item.end))) return null; model.items = payload.items.map((item) => visibleCard(item.id, `Calendar item ${text(item.id, 80)}`, `${iso(item.start)} · ${text(item.timezone, 80)}`, item.status, "Calendar", "SAFE", "complete", "demo")).filter(Boolean); }
  else if (route === "tasks") { if (payload.items.some((item) => !exactKeys(item, ["id", "title", "status", "source", "version"]) || hasSentinel(item) || typeof item.version !== "number")) return null; model.items = payload.items.map((item) => visibleCard(item.id, `Task ${text(item.id, 80)}`, `Источник: ${text(item.source, 80)}`, item.status, item.source, "SAFE", "complete", "task")).filter(Boolean); }
  else if (route === "reviews") { if (payload.items.some((item) => !exactKeys(item, ["id", "target_id", "status", "finding_count"]) || hasSentinel(item) || typeof item.finding_count !== "number")) return null; model.items = payload.items.map((item) => visibleCard(item.id, `Review ${text(item.id, 80)}`, `Target: ${text(item.target_id, 80)} · findings: ${item.finding_count}`, item.status, "Controller", "SAFE", "complete", "review")).filter(Boolean); }
  else if (route === "memory-metadata") { if (payload.items.some((item) => !exactKeys(item, ["id", "scope", "sensitivity", "status", "provenance_count"]) || hasSentinel(item) || typeof item.provenance_count !== "number")) return null; model.items = payload.items.map((item) => visibleCard(item.id, `Memory ref ${text(item.id, 80)}`, `Scope: ${text(item.scope, 80)} · provenance: ${item.provenance_count}`, item.status, "Beads", item.sensitivity, "complete", "memory")).filter(Boolean); }
  return hasSentinel(model) ? null : model;
}

function syntheticProjection(route) { if (!state.synthetic) return emptyModel(route); const items = SYNTHETIC_READ_MODEL.items?.[route] || SYNTHETIC_READ_MODEL.items?.[route === "workgraph" ? "graph" : route] || []; return { ...emptyModel(route), state: "synthetic", generated_at: SYNTHETIC_READ_MODEL.generatedAt, items: items.map((item) => visibleCard(item.id, item.title, item.detail, item.status, item.source, item.privacy, item.coverage, item.kind)).filter(Boolean), metrics: SYNTHETIC_READ_MODEL.metrics, health: SYNTHETIC_READ_MODEL.health }; }
function el(tag, content, className) { const node = document.createElement(tag); if (className) node.className = className; if (content !== undefined) node.textContent = text(content); return node; }
function badge(value) { const kind = ["ready", "confirmed", "complete", "SAFE", "active", "running", "accepted"].includes(value) ? "good" : ["blocked", "UNKNOWN", "stale", "best_effort", "pending", "candidate", "review"].includes(value) ? "warn" : "neutral"; return el("span", value || "unknown", `badge badge-${kind}`); }
function renderNav() { const nav = $("route-nav"); nav.replaceChildren(); for (const [id, label] of ROUTES) { const button = el("button", label, "nav-link"); button.type = "button"; button.dataset.route = id; button.classList.toggle("active", state.route === id); button.setAttribute("aria-current", state.route === id ? "page" : "false"); button.addEventListener("click", () => navigate(id)); nav.append(button); } }
function navigate(route) { state.route = route; window.history.replaceState(null, "", `?route=${encodeURIComponent(route)}${state.synthetic ? "&synthetic=1" : ""}`); renderNav(); render(); $("main").focus(); loadRoute(route); }
function heading(kicker, title, note) { const head = el("div", undefined, "section-heading"); const left = el("div"); left.append(el("p", kicker, "eyebrow"), el("h2", title)); head.append(left, el("span", note, "muted")); return head; }
function card(item) { const article = el("article", undefined, "card"); const top = el("div", undefined, "row"); top.append(el("span", item.title, "row-title"), badge(item.status)); article.append(top, el("p", item.detail)); const meta = el("div", undefined, "row"); meta.append(el("span", `${item.source} · ${item.kind}`, "muted")); const labels = el("span"); labels.append(badge(item.privacy), badge(item.coverage)); meta.append(labels); article.append(meta); return article; }
function cards(items, empty = "Нет доступных элементов") { const grid = el("div", undefined, "grid"); if (!items?.length) grid.append(el("p", empty, "empty")); else items.forEach((item) => grid.append(card(item))); return grid; }
function render() { const model = state.model || syntheticProjection(state.route); const view = $("view"); view.replaceChildren(); const title = ROUTES.find(([id]) => id === state.route)?.[1] || "Сегодня"; if (state.synthetic) view.append(el("div", "SYNTHETIC DEV FIXTURE · реальные данные отключены", "banner banner-warn")); if (state.route === "health") renderHealth(view, model); else view.append(heading(state.synthetic ? "Synthetic read model" : "Controller read model", title, model.generated_at ? `Срез: ${model.generated_at}` : "Нет данных"), cards(model.items)); }
function renderHealth(view, model) { view.append(heading("Runtime", "Здоровье системы", "metadata-only projection")); const health = model.health; if (!health) { view.append(cards([], "Health read model недоступен")); return; } const grid = el("div", undefined, "grid"); [["Controller", health.status], ["Controller доступен", String(health.controller_available)], ["Effects", health.effects_enabled ? "enabled" : "disabled"]].forEach(([label, value]) => { const item = el("article", undefined, "card"); item.append(el("div", label, "muted"), badge(value)); grid.append(item); }); view.append(grid); }
function approvalLocked(now = Date.now()) { return Boolean(state.approval && now < state.approval.expiresAt); }
function syncApprovalLock() { const locked = approvalLocked(); const composer = $("composer"); composer.disabled = locked; $("composer-submit").disabled = locked || state.controller !== "ready" || state.synthetic; return locked; }
function clearApproval() { state.approval = null; $("owner-approval-retry").hidden = true; $("owner-approval-retry").disabled = true; syncApprovalLock(); }
function expireApproval() { clearApproval(); renderAssistantResult({ schema_version: CHAT_RESULT_SCHEMA, chat_id: "chat", state: "failed", error_code: "OWNER_APPROVAL_EXPIRED", started_at: new Date().toISOString() }); }
function setHealth(controller, message) { state.controller = controller; $("health-dot").className = `dot ${controller === "ready" ? "dot-good" : "dot-warn"}`; $("health-label").textContent = message; syncApprovalLock(); $("degraded-banner").hidden = controller === "ready" && !state.synthetic; if (controller !== "ready" || state.synthetic) $("degraded-banner").textContent = state.synthetic ? "Synthetic dev mode: реальные данные и эффекты отключены." : "Controller недоступен или сессия истекла: read-only projection без данных. Запросы и эффекты заблокированы."; }
function clearAuth(message = "Controller: недоступен") { state.auth = null; state.model = null; setHealth("degraded_read_only", message); render(); }
async function bootstrap() { if (state.auth && Date.now() < state.auth.expiresAt) return true; state.auth = null; try { const response = await fetch("/v1/ui/bootstrap", { method: "POST", credentials: "omit", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ client_nonce: nonce("client") }), cache: "no-store" }); const session = await response.json(); if (!response.ok || !validSession(session) || Date.parse(session.expires_at) <= Date.now()) return false; state.auth = { token: session.token, clientNonce: session.client_nonce, expiresAt: Date.parse(session.expires_at) }; return true; } catch (_error) { return false; } }
async function controllerFetch(path, options = {}) { if (!(await bootstrap()) || !state.auth || Date.now() >= state.auth.expiresAt) return null; const requestNonce = nonce("request"); const headers = new Headers(options.headers || {}); headers.set("Authorization", `Bearer ${state.auth.token}`); headers.set("X-UI-Nonce", state.auth.clientNonce); headers.set("X-UI-Request-Nonce", requestNonce); try { const response = await fetch(path, { ...options, credentials: "omit", headers, cache: "no-store" }); if (response.status === 401 || response.status === 403) { clearAuth("Controller: сессия истекла или отклонена"); return null; } return response; } catch (_error) { clearAuth("Controller: сетевой запрос завершился ошибкой"); return null; } }
async function pollChatRun(runId, attempts = 12) { if (typeof runId !== "string" || !runId || attempts < 1 || attempts > 60) return null; for (let i = 0; i < attempts; i++) { const response = await controllerFetch(`/v1/chat/runs/${encodeURIComponent(runId)}`, { headers: { Accept: "application/json" } }); if (!response) return null; try { const result = await response.json(); if (!validAssistantResult(result)) return null; renderAssistantResult(result); if (["completed", "failed", "cancelled"].includes(result.state)) return result; } catch (_error) { return null; } await new Promise((resolve) => setTimeout(resolve, 250)); } return null; }
async function cancelChatRun(runId) { if (typeof runId !== "string" || !runId) return false; const response = await controllerFetch(`/v1/chat/runs/${encodeURIComponent(runId)}`, { method: "DELETE", headers: { Accept: "application/json" } }); return Boolean(response && response.ok); }
async function loadRoute(route) { const wireRoute = READ_ROUTE[route]; if (!wireRoute) { state.model = emptyModel(route); render(); return; } const response = await controllerFetch(`/v1/read/${wireRoute}`, { headers: { Accept: "application/json" } }); if (!response) return; try { const payload = await response.json(); const model = response.ok ? validateRead(wireRoute, payload) : null; state.model = model ? { ...model, route } : emptyModel(route); setHealth(model ? "ready" : "degraded_read_only", model ? "Controller: готов" : "Controller: invalid read model"); } catch (_error) { state.model = emptyModel(route); setHealth("degraded_read_only", "Controller: invalid response"); } render(); }
function showApproval(approval) { const output = $("chat-result"); output.hidden = false; output.className = "result"; output.textContent = `Требуется подтверждение владельца до ${approval.expires_at}. Выполните: sudo '/Library/Application Support/OpenDuck/operator/openduck-owner-grant' — затем нажмите «Повторить».`; const retry = $("owner-approval-retry"); retry.hidden = false; retry.disabled = false; syncApprovalLock(); }
async function startChat(body, requestId = "") { const headers = { "Content-Type": "application/json", Accept: "application/json" }; if (requestId) Object.assign(headers, approvalRetryHeaders(requestId)); const response = await controllerFetch("/v1/chat/runs", { method: "POST", headers, body }); if (!response) return null; let result; try { result = await response.json(); } catch (_error) { return null; } if (response.status === 428 && validApprovalRequired(result)) { state.approval = { body, requestId: result.request_id, expiresAt: Date.parse(result.expires_at) }; showApproval(result); return "approval"; } if (!response.ok || !validAssistantResult(result)) return null; clearApproval(); renderAssistantResult(result); const cancel = $("chat-cancel"); cancel.hidden = false; cancel.disabled = false; cancel.onclick = async () => { await cancelChatRun(result.chat_id); cancel.disabled = true; }; await pollChatRun(result.chat_id, 60); cancel.hidden = true; return result; }
async function submitComposer(event) { event.preventDefault(); if (state.approval) { if (!approvalLocked()) expireApproval(); else syncApprovalLock(); return; } const composer = $("composer"); const raw = composer.value; if (!raw || raw.length > 8000 || state.controller !== "ready" || state.synthetic) return; $("composer-submit").disabled = true; const result = await startChat(serializeChatOrder(nonce("chat"), raw)); if (!result) renderAssistantResult({ schema_version: CHAT_RESULT_SCHEMA, chat_id: "chat", state: "failed", error_code: "INVALID_RESPONSE", started_at: new Date().toISOString() }); if (result && result !== "approval") composer.value = ""; syncApprovalLock(); }
async function retryOwnerApproval() { const pending = state.approval; if (!pending || !approvalLocked()) { expireApproval(); return; } const retry = $("owner-approval-retry"); retry.disabled = true; const result = await startChat(pending.body, pending.requestId); if (!result) renderAssistantResult({ schema_version: CHAT_RESULT_SCHEMA, chat_id: "chat", state: "failed", error_code: "INVALID_RESPONSE", started_at: new Date().toISOString() }); if (state.approval) retry.disabled = false; }

if (typeof document !== "undefined") { $("composer-form").addEventListener("submit", submitComposer); $("owner-approval-retry").addEventListener("click", retryOwnerApproval); renderNav(); setHealth("degraded_read_only", "Инициализация UI-сессии…"); render(); if (state.synthetic) { setHealth("ready", "Synthetic dev mode · реальные данные отключены"); render(); } else bootstrap().then((ok) => { if (!ok) clearAuth(); else { setHealth("ready", "Controller: сессия установлена"); loadRoute(state.route); } }); }

export { ROUTES, READ_ROUTE, state, approvalLocked, syncApprovalLock, clearApproval, expireApproval, submitComposer, showApproval, hasSentinel, validateRead, validSession, validAssistantResult, validApprovalRequired, serializeChatOrder, approvalRetryHeaders, renderAssistantResult, pollChatRun, cancelChatRun, withinBounds };
