import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import plugin, { hasCanonicalPdMarker, hasPdNearMiss, PDPolicy } from "./index.mjs";

assert.equal(hasCanonicalPdMarker("Это ПД\nтекст"), true);
assert.equal(hasCanonicalPdMarker(" это ПД\n"), false);
assert.equal(hasCanonicalPdMarker("Это ПД\r\n"), true);
assert.equal(hasCanonicalPdMarker("Это ПДЕ\n"), false);
assert.equal(hasCanonicalPdMarker("Это ПД\u200b\n"), false);
assert.equal(hasPdNearMiss("Это П-Д\n"), true);
assert.equal(hasPdNearMiss("Ето PД\n"), true);
assert.equal(hasPdNearMiss("Это ПД\u200b\n"), true);
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pd-router-")); const state = path.join(dir, "state.json");
let p = new PDPolicy({ statePath: state });
assert.equal(p.mode("s", "Это ПД\n"), "pd");
assert.deepEqual(p.beforeModelResolve({ sessionKey: "s", prompt: "x" }), { providerOverride: "ollama", modelOverride: "qwen3:8b" });
assert.equal(p.beforeToolCall({ sessionKey: "s", toolName: "web_search" }).block, true);
p = new PDPolicy({ statePath: state }); assert.equal(p.mode("s", "normal"), "pd");
const upgrade = new PDPolicy({ statePath: path.join(dir, "upgrade.json") }); assert.equal(upgrade.mode("u", "обычный текст"), "normal"); assert.equal(upgrade.mode("u", "Это ПД\n"), "pd");
const quarantinePath = path.join(dir, "quarantine.json"); const quarantine = new PDPolicy({ statePath: quarantinePath }); assert.equal(quarantine.mode("q", "Это П-Д\n"), "quarantine"); const restartedQuarantine = new PDPolicy({ statePath: quarantinePath }); assert.equal(restartedQuarantine.mode("q", "normal"), "quarantine"); assert.equal(restartedQuarantine.beforeAgentRun({ sessionKey: "q", provider: "openai", model: "gpt" }).outcome, "block");
assert.equal(new PDPolicy({ statePath: path.join(dir, "empty.json") }).mode("", "Это ПД\n"), "deny");
fs.writeFileSync(state, "corrupt"); p = new PDPolicy({ statePath: state }); assert.equal(p.mode("x", "normal"), "deny");
const hooks = new Map(); let trusted;
plugin.register({ pluginConfig: { statePath: path.join(dir, "plugin.json") }, on: (name, fn) => hooks.set(name, fn), registerTrustedToolPolicy: (x) => { trusted = x; } });
assert.ok(hooks.has("before_model_resolve") && hooks.has("before_agent_run") && hooks.has("before_tool_call")); assert.equal(trusted.id, "pd-router");
assert.deepEqual(await hooks.get("before_model_resolve")({ prompt: "Это ПД\n" }, { sessionKey: "hook-pd" }), { providerOverride: "ollama", modelOverride: "qwen3:8b" });
assert.equal((await hooks.get("before_agent_run")({ prompt: "normal" }, { sessionKey: "hook-pd", modelProviderId: "openai", modelId: "gpt" })).outcome, "block");
assert.equal((await hooks.get("before_tool_call")({ toolName: "x" }, { sessionKey: "hook-pd" })).block, true);
console.log("pd-router tests passed");
