import React, { useCallback, useEffect, useRef, useState } from 'react'
import { Button } from '@deepseek-ai/dsh-client-ui-primitives'
type Provider = 'codex' | 'claude' | 'kimi'; type Project = { id: string; displayName: string }; type Session = { sessionId: string; title?: string; preview?: string }; type Message = { id: string; role: 'user' | 'assistant'; text: string }; type Page<T> = { items: T[]; nextCursor: string | null }
export type HistoryRpc = { call: (channel: string, endpoint: string, payload: unknown, signal?: AbortSignal) => Promise<{ ok: boolean; value?: unknown }> }
const providers: readonly Provider[] = ['codex', 'claude', 'kimi']
function page<T>(value: unknown, valid: (item: unknown) => item is T): Page<T> | undefined { if (value === null || typeof value !== 'object' || !Array.isArray((value as { items?: unknown }).items)) return undefined; const raw = (value as { items: unknown[] }).items; if (!raw.every(valid)) return undefined; const cursor = (value as { nextCursor?: unknown }).nextCursor; return { items: raw, nextCursor: typeof cursor === 'string' ? cursor : null } }
const validProject = (item: unknown): item is Project => Boolean(item && typeof item === 'object' && typeof (item as Project).id === 'string' && typeof (item as Project).displayName === 'string')
const validSession = (item: unknown): item is Session => Boolean(item && typeof item === 'object' && typeof (item as Session).sessionId === 'string')
const validMessage = (item: unknown): item is Message => Boolean(item && typeof item === 'object' && typeof (item as Message).id === 'string' && ((item as Message).role === 'user' || (item as Message).role === 'assistant') && typeof (item as Message).text === 'string')
/** Read-only viewer for host-normalized external CLI history. */
export const HistoryViewer = ({ rpc }: { rpc: HistoryRpc }) => {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(''); const [provider, setProvider] = useState<Provider>('codex'); const [sessions, setSessions] = useState<Session[]>([]); const [sessionCursor, setSessionCursor] = useState<string | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [messageCursor, setMessageCursor] = useState<string | null>(null); const [selectedSession, setSelectedSession] = useState(''); const [loading, setLoading] = useState<'projects' | 'sessions' | 'messages' | ''>('projects'); const [error, setError] = useState(''); const requestId = useRef(0)
  const resetHistory = (): void => { setSessions([]); setSessionCursor(null); setMessages([]); setMessageCursor(null); setSelectedSession(''); setError('') }
  const loadProjects = useCallback(async () => { const id = ++requestId.current; setLoading('projects'); setError(''); try { const result = await rpc.call('/openduck-history', 'projects', {}); const resultPage = page(result.value, validProject); if (!result.ok || !resultPage || id !== requestId.current) throw new Error(); setProjects(resultPage.items); setProjectId(current => resultPage.items.some(project => project.id === current) ? current : resultPage.items[0]?.id ?? ''); resetHistory() } catch { if (id === requestId.current) setError('History is unavailable.') } finally { if (id === requestId.current) setLoading('') } }, [rpc])
  useEffect(() => { void loadProjects() }, [loadProjects])
  const loadSessions = async (cursor?: string): Promise<void> => { if (!projectId) return; const id = ++requestId.current; setLoading('sessions'); setError(''); try { const result = await rpc.call('/openduck-history', 'sessions', { projectId, provider, limit: 25, ...(cursor ? { cursor } : {}) }); const resultPage = page(result.value, validSession); if (!result.ok || !resultPage || id !== requestId.current) throw new Error(); setSessions(current => cursor ? [...current, ...resultPage.items] : resultPage.items); setSessionCursor(resultPage.nextCursor); setMessages([]); setMessageCursor(null); setSelectedSession('') } catch { if (id === requestId.current) setError('History is unavailable.') } finally { if (id === requestId.current) setLoading('') } }
  const loadMessages = async (sessionId: string, cursor?: string): Promise<void> => { if (!projectId) return; const id = ++requestId.current; setLoading('messages'); setError(''); try { const result = await rpc.call('/openduck-history', 'messages', { projectId, provider, sessionId, limit: 100, ...(cursor ? { cursor } : {}) }); const resultPage = page(result.value, validMessage); if (!result.ok || !resultPage || id !== requestId.current) throw new Error(); setMessages(current => cursor ? [...current, ...resultPage.items] : resultPage.items); setMessageCursor(resultPage.nextCursor); setSelectedSession(sessionId) } catch { if (id === requestId.current) setError('History is unavailable.') } finally { if (id === requestId.current) setLoading('') } }
  const chooseProject = (value: string): void => { setProjectId(value); requestId.current += 1; resetHistory() }; const chooseProvider = (value: Provider): void => { setProvider(value); requestId.current += 1; resetHistory() }
  return <section style={{ display: 'grid', gap: 14, minWidth: 0 }}>
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, alignItems: 'end' }}>
      <label style={{ display: 'grid', gap: 4 }}>Project <select value={projectId} onChange={event => chooseProject(event.target.value)} disabled={loading === 'projects'}>{projects.map(project => <option key={project.id} value={project.id}>{project.displayName}</option>)}</select></label>
      <label style={{ display: 'grid', gap: 4 }}>Provider <select value={provider} onChange={event => chooseProvider(event.target.value as Provider)} disabled={loading === 'projects'}>{providers.map(item => <option key={item}>{item}</option>)}</select></label>
      <Button onClick={() => void loadProjects()} disabled={loading !== ''}>Refresh projects</Button><Button onClick={() => void loadSessions()} disabled={!projectId || loading !== ''}>Load sessions</Button>
    </div>
    {loading && <p role="status">Loading {loading}…</p>}{error && <p role="alert">{error}</p>}
    {!loading && !error && projects.length === 0 && <p role="status">Add a project in OpenDuck settings to view history.</p>}
    {!loading && !error && projectId && sessions.length === 0 && <p role="status">No sessions loaded.</p>}
    {sessions.length > 0 && <div><h3>Sessions</h3><div style={{ display: 'grid', gap: 8, maxHeight: 220, overflow: 'auto' }}>{sessions.map(session => <div key={session.sessionId} style={{ display: 'flex', gap: 8, alignItems: 'baseline' }}><Button onClick={() => void loadMessages(session.sessionId)} disabled={loading !== ''}>{session.title || session.sessionId}</Button><span style={{ overflowWrap: 'anywhere' }}>{session.preview || ''}</span></div>)}</div>{sessionCursor && <Button onClick={() => void loadSessions(sessionCursor)} disabled={loading !== ''}>Load more sessions</Button>}</div>}
    {selectedSession && <div><h3>Messages</h3>{!loading && messages.length === 0 && <p role="status">No messages are available for this session.</p>}<ol style={{ display: 'grid', gap: 10, maxHeight: 360, overflow: 'auto', paddingLeft: 22 }}>{messages.map(message => <li key={message.id} style={{ overflowWrap: 'anywhere', whiteSpace: 'pre-wrap' }}><strong>{message.role === 'user' ? 'You' : 'Assistant'}</strong><div>{message.text}</div></li>)}</ol>{messageCursor && <Button onClick={() => void loadMessages(selectedSession, messageCursor)} disabled={loading !== ''}>Load more messages</Button>}</div>}
  </section>
}
