// Package sensor contains the narrow, local-only ingress boundary for the
// local sensor. It accepts authenticated synthetic events and emits only a
// typed TaskSignal to the Controller. The sensor is never a source of effect
// authority or a model/tool surface.
package sensor

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"time"

	"openduck/internal/core"
	"openduck/internal/harness"
)

const (
	EnvelopeSchema = "sensor-envelope.v1"
	PolicyVersion  = "sensor-ingress.v1"
	MaxBodyBytes   = 64 << 10
)

var (
	ErrUnauthorized = errors.New("sensor authentication failed")
	ErrReplay       = errors.New("sensor request replayed")
	ErrSensitive    = errors.New("sensor event quarantined")
	ErrInjection    = errors.New("sensor content rejected")
	ErrNotLocal     = errors.New("sensor peer is not loopback")
)

// Envelope is the only wire shape accepted by the transport. RequestID and
// Nonce are generated by the sender, but are authenticated and replay checked;
// no sender-controlled field is used as an authority or as a task identity.
type Envelope struct {
	SchemaVersion string            `json:"schema_version"`
	RequestID     string            `json:"request_id"`
	Nonce         string            `json:"nonce"`
	IssuedAt      time.Time         `json:"issued_at"`
	Event         core.InboundEvent `json:"event"`
	Signature     string            `json:"signature"`
}

type Projector interface {
	IngestSignal(context.Context, string, harness.TaskSignal) (harness.TaskRecord, error)
}

// Transport is deliberately dependency-injected. Queue should normally be a
// core.FileQueue backed by a Keychain-derived key; tests may use MemoryQueue.
type Transport struct {
	key       []byte
	queue     core.Queue
	projector Projector
	now       func() time.Time
	maxSkew   time.Duration
	mu        sync.Mutex
	seen      map[string]time.Time
	replay    *replayStore
}

// DeriveKeys creates purpose-separated subkeys from the Controller state key.
// The master key is never retained by the sensor package.
func DeriveKeys(master []byte) (sensorHMAC, queueKey []byte, err error) {
	if len(master) != 32 {
		return nil, nil, errors.New("master key must be 32 bytes")
	}
	derive := func(purpose string) []byte {
		h := hmac.New(sha256.New, master)
		_, _ = h.Write([]byte("openduck/key/" + purpose + "/v1"))
		return h.Sum(nil)
	}
	return derive("sensor-hmac"), derive("sensor-queue"), nil
}

// Client is the narrow sender seam used by a sensor process. It
// owns the signing key but exposes no key material to the caller.
type Client struct {
	key        []byte
	now        func() time.Time
	base       string
	httpClient *http.Client
}

func NewClient(key []byte, base string) (*Client, error) {
	if len(key) != 32 || base != "http://127.0.0.1:8788/v1/sensor/events" {
		return nil, errors.New("invalid sensor client configuration")
	}
	transport := &http.Transport{Proxy: nil, DialContext: func(ctx context.Context, network, address string) (net.Conn, error) {
		if network != "tcp" || address != "127.0.0.1:8788" {
			return nil, ErrNotLocal
		}
		return (&net.Dialer{Timeout: 2 * time.Second}).DialContext(ctx, network, address)
	}}
	return &Client{key: append([]byte(nil), key...), now: time.Now, base: base, httpClient: &http.Client{Transport: transport, Timeout: 5 * time.Second, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}}, nil
}

func (c *Client) Close() {
	for i := range c.key {
		c.key[i] = 0
	}
	if c.httpClient != nil {
		c.httpClient.CloseIdleConnections()
	}
}

func (c *Client) Sign(event core.InboundEvent) (Envelope, error) {
	if err := event.Validate(); err != nil {
		return Envelope{}, err
	}
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return Envelope{}, err
	}
	e := Envelope{SchemaVersion: EnvelopeSchema, RequestID: "req_" + hex.EncodeToString(b), Nonce: "n_" + hex.EncodeToString(b), IssuedAt: c.now().UTC(), Event: event}
	h := hmac.New(sha256.New, c.key)
	e.Signature = ""
	raw, _ := json.Marshal(e)
	_, _ = h.Write(raw)
	e.Signature = "hmac-sha256:" + hex.EncodeToString(h.Sum(nil))
	return e, nil
}

func New(key []byte, queue core.Queue, projector Projector) (*Transport, error) {
	if len(key) != 32 || queue == nil || projector == nil {
		return nil, errors.New("sensor requires a 32-byte key, queue, and projector")
	}
	return &Transport{key: append([]byte(nil), key...), queue: queue, projector: projector, now: time.Now, maxSkew: 2 * time.Minute, seen: make(map[string]time.Time)}, nil
}

func NewWithReplay(key []byte, replayKey []byte, queue core.Queue, projector Projector, replayPath string) (*Transport, error) {
	t, err := New(key, queue, projector)
	if err != nil {
		return nil, err
	}
	r, err := newReplayStore(replayPath, replayKey)
	if err != nil {
		return nil, err
	}
	t.replay = r
	return t, nil
}

func (t *Transport) Issue(event core.InboundEvent) (Envelope, error) {
	if err := event.Validate(); err != nil {
		return Envelope{}, err
	}
	requestID, err := randomID("req_")
	if err != nil {
		return Envelope{}, err
	}
	nonce, err := randomID("n_")
	if err != nil {
		return Envelope{}, err
	}
	e := Envelope{SchemaVersion: EnvelopeSchema, RequestID: requestID, Nonce: nonce, IssuedAt: t.now().UTC(), Event: event}
	e.Signature = t.sign(e)
	return e, nil
}

func (t *Transport) sign(e Envelope) string {
	e.Signature = ""
	b, _ := json.Marshal(e)
	h := hmac.New(sha256.New, t.key)
	_, _ = h.Write(b)
	return "hmac-sha256:" + hex.EncodeToString(h.Sum(nil))
}

func (t *Transport) accept(ctx context.Context, e Envelope) (harness.TaskRecord, error) {
	if err := t.authenticate(e); err != nil {
		return harness.TaskRecord{}, err
	}
	if err := t.reserve(e); err != nil {
		return harness.TaskRecord{}, err
	}
	if err := validateContent(e.Event); err != nil {
		return harness.TaskRecord{}, err
	}
	// Queue first: Controller projection is a derivative. A projection failure
	// leaves the encrypted queue item available for deterministic reconciliation.
	if _, err := t.queue.Enqueue(ctx, e.Event); err != nil {
		return harness.TaskRecord{}, err
	}
	signal, taskID, err := compileSignal(e)
	if err != nil {
		return harness.TaskRecord{}, err
	}
	return t.projector.IngestSignal(ctx, taskID, signal)
}

func (t *Transport) authenticate(e Envelope) error {
	if e.SchemaVersion != EnvelopeSchema || e.RequestID == "" || e.Nonce == "" || e.IssuedAt.IsZero() || e.Signature == "" {
		return ErrUnauthorized
	}
	if !hmac.Equal([]byte(e.Signature), []byte(t.sign(e))) {
		return ErrUnauthorized
	}
	delta := t.now().Sub(e.IssuedAt)
	if delta < -t.maxSkew || delta > t.maxSkew {
		return ErrUnauthorized
	}
	return nil
}

func (t *Transport) reserve(e Envelope) error {
	if t.replay != nil {
		return t.replay.reserve(e.RequestID+"\x00"+e.Nonce, t.now(), t.maxSkew)
	}
	t.mu.Lock()
	defer t.mu.Unlock()
	now := t.now()
	for k, at := range t.seen {
		if now.Sub(at) > t.maxSkew {
			delete(t.seen, k)
		}
	}
	if _, ok := t.seen[e.RequestID+"\x00"+e.Nonce]; ok {
		return ErrReplay
	}
	t.seen[e.RequestID+"\x00"+e.Nonce] = now
	return nil
}

// Handler exposes only a POST endpoint. The listener must itself bind to a
// loopback address; the peer check below is defense in depth for accidental
// non-loopback composition.
func (t *Transport) Handler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			w.Header().Set("Allow", http.MethodPost)
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if err := loopbackPeer(r.RemoteAddr); err != nil {
			http.Error(w, err.Error(), http.StatusForbidden)
			return
		}
		r.Body = http.MaxBytesReader(w, r.Body, MaxBodyBytes)
		dec := json.NewDecoder(r.Body)
		dec.DisallowUnknownFields()
		var e Envelope
		if err := dec.Decode(&e); err != nil {
			http.Error(w, "invalid sensor envelope", http.StatusBadRequest)
			return
		}
		record, err := t.accept(r.Context(), e)
		if err != nil {
			code := http.StatusBadRequest
			if errors.Is(err, ErrUnauthorized) || errors.Is(err, ErrReplay) {
				code = http.StatusUnauthorized
			} else if errors.Is(err, ErrSensitive) || errors.Is(err, ErrInjection) {
				code = http.StatusUnprocessableEntity
			}
			http.Error(w, err.Error(), code)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"accepted": true, "task_id": record.ID, "state": record.State, "schema_version": "sensor-ack.v1"})
	})
}

func loopbackPeer(remote string) error {
	host, _, err := net.SplitHostPort(remote)
	if err != nil {
		return ErrNotLocal
	}
	ip := net.ParseIP(host)
	if ip == nil || !ip.IsLoopback() {
		return ErrNotLocal
	}
	return nil
}

// deterministicIngressScanner is a conservative, local policy scanner. It is
// intentionally distinct from core.DLP's model-facing classification API.
var injectionPattern = regexp.MustCompile(`(?i)(ignore\s+(all|any|the)\s+previous|system\s+message|developer\s+message|call\s+the\s+tool|execute\s+command|codex_delegate|<\s*(script|iframe)\b)`)
var pdPattern = regexp.MustCompile(`(?i)(это\s+пд|персональн(?:ые|ая)\s+данн|passport|паспорт|ssn|iban|sk-[A-Za-z0-9]{16,}|ghp_[A-Za-z0-9]{20,})`)
var emailPattern = regexp.MustCompile(`(?i)\b[\w.+-]+@[\w.-]+\.[a-z]{2,}\b`)
var phonePattern = regexp.MustCompile(`\+?[0-9][0-9 ()-]{8,}[0-9]`)

func validateContent(e core.InboundEvent) error {
	if strings.TrimSpace(e.Text) == "" || len(e.Text) > 16000 {
		return ErrSensitive
	}
	if injectionPattern.MatchString(e.Text) {
		return ErrInjection
	}
	if pdPattern.MatchString(e.Text) || e.Classification.Rank() > core.L1.Rank() || emailPattern.MatchString(e.Text) || phonePattern.MatchString(e.Text) {
		return ErrSensitive
	}
	if strings.ContainsAny(e.Text, "\x00\r\n\u202e\u202d\u200b\u200c\u200d") {
		return ErrInjection
	}
	return nil
}

func compileSignal(e Envelope) (harness.TaskSignal, string, error) {
	if err := e.Event.Validate(); err != nil {
		return harness.TaskSignal{}, "", err
	}
	h := sha256.Sum256([]byte(e.Event.Provenance.AdapterID + "\x00" + e.Event.Provenance.AccountID + "\x00" + e.Event.Provenance.SourceEventID))
	taskID := "task_" + hex.EncodeToString(h[:16])
	s := harness.TaskSignal{SchemaVersion: harness.TaskSignalV1, SignalID: "sig_" + e.RequestID, SourceRef: "inbound:" + e.Event.ID, SourceVersion: e.Event.Provenance.Version, ObservedAt: e.Event.Provenance.Timestamp.UTC(), Kind: "message", Summary: e.Event.Text, Facts: []harness.Fact{}, Urgency: "normal", MaxClass: "L1", Coverage: harness.Coverage{Complete: true, GapRefs: []string{}}, EvidenceRefs: []string{"inbound:" + e.Event.ID}, SuggestedRoute: "root", PolicyVersion: PolicyVersion}
	if err := s.Seal(); err != nil {
		return harness.TaskSignal{}, "", fmt.Errorf("seal signal: %w", err)
	}
	return s, taskID, nil
}

func randomID(prefix string) (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return prefix + hex.EncodeToString(b), nil
}
